version: "3"

tasks:
  start:
    desc: "Starts the Go HTTP server"
    cmds:
      - go run main.go
    silent: false

  docs:
    desc : "Generate Swagger Docs"
    cmds:
      - swag init -o ./docs/swagger
    silent: false

  default:
    cmds:
      - task: start
